// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dotnetcore.Data.Migrations
{
    [DbContext(typeof(apDBcontext))]
    [Migration("20221106093711_FirtstMigration")]
    partial class FirtstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Data.Post", b =>
                {
                    b.Property<int>("postId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("postId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            postId = 1,
                            Content = "the contnet post 1 this is the contntent",
                            Title = "title post 1"
                        },
                        new
                        {
                            postId = 2,
                            Content = "the contnet post 2 this is the contntent",
                            Title = "title post 2"
                        },
                        new
                        {
                            postId = 3,
                            Content = "the contnet post 3 this is the contntent",
                            Title = "title post 3"
                        },
                        new
                        {
                            postId = 4,
                            Content = "the contnet post 4 this is the contntent",
                            Title = "title post 4"
                        },
                        new
                        {
                            postId = 5,
                            Content = "the contnet post 5 this is the contntent",
                            Title = "title post 5"
                        },
                        new
                        {
                            postId = 6,
                            Content = "the contnet post 6 this is the contntent",
                            Title = "title post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
